version: '3'

volumes:
  pga4volume:
    external: true
  backend_volume:
    external: true



services:
  rbac_postgres:
    image: postgres:10.6-alpine
    ports:
      - 6999:5432
    volumes:
      - backend_volume:/var/lib/pgadmin
    environment:
      PG_MODE: primary
      PG_PRIMARY_USER: postgres
      PG_PRIMARY_PORT: 5432

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - pga4volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: wbekalti@batvoice.com
      PGADMIN_DEFAULT_PASSWORD: batvoice
      SERVER_PORT: 80
